import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { sanityClient, SanityClient, urlFor } from '../lib/sanity';

// const recipesQuery = `*[_type == "recipe"]`; // to see out put for this go to groq.dev
const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({ recipes }) {
  return (
    <div>
      <Head>
        <title>recipe app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>Welcome to the app</h1>

      <ul className='recipesList'>
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li className='recipeCard' key={recipe._id}>
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <div className='image'>
                    <Image
                      width={300}
                      height={300}
                      layout='responsive'
                      src={urlFor(recipe.mainImage).url()}
                    />
                  </div>
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipesQuery);
  return { props: { recipes } };
}
