import Navbar from '@/components/navbar';
import './globals.css';
// import { HelveticaNeueLTPro } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
// const helvetica = HelveticaNeueLTPro({ subsets: ['latin'] });

export const metadata = {
  title: 'ClayStack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <body className={helvetica.className}> */}
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
