import Navbar from '@/components/navbar';
import './globals.css';
import Footer from '@/components/footer';
// import localFont from 'next/font/local'
// import { HelveticaNeueLTPro } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
// const helvetica = HelveticaNeueLTPro({ subsets: ['latin'] });

// const myFont = localFont({ src: '/font/Helvetica-Neue-LT-Std' })

export const metadata = {
  title: 'ClayStack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* <body className={helvetica.className}> */}
      {/* <body className={myFont.className}> */}
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
